In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics 
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, explained_variance_score
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsClassifier

In [29]:
dataframe = pd.read_csv(r"dataset_urls.csv")

In [30]:
dataframe.rename(columns = {'type':'label'}, inplace = True)
dataframe = dataframe.drop('url', axis = 1)
dataframe.head()

y = dataframe.label
x = dataframe.drop('label', axis=1)
print(x)
print(y)

       MU_dots  MU_hypens  MU_at  MU_and  MU_percentage  MU_slash  MU_star  \
0            2         12      0       0              0         3        0   
1            2          1      0       0              0         7        0   
2            2          0      0       0              0         4        0   
3            1          1      0       0             20         6        0   
4            3          1      0       0              1         8        0   
...        ...        ...    ...     ...            ...       ...      ...   
19795        3          2      0       0              0         5        0   
19796        2          0      0       0              0         5        0   
19797        2          0      0       0              0         4        0   
19798        5          1      0       0              0         8        0   
19799        2          1      0       0              0         7        0   

       MU_comma  MU_semicolon  MU_dollar  ...  MU_underscore  M

In [32]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [33]:
print("shape of original dataset :", dataframe.shape)
print("shape of input - training set", x_train.shape)
print("shape of output - training set", y_train.shape)
print("shape of input - testing set", x_test.shape)
print("shape of output - testing set", y_test.shape)

shape of original dataset : (19800, 24)
shape of input - training set (15840, 23)
shape of output - training set (15840,)
shape of input - testing set (3960, 23)
shape of output - testing set (3960,)


## __Random Forest Classification using Scikit Learn__

In [43]:
clf = RandomForestClassifier(n_estimators = 100) 
clf.fit(x_train, y_train)
y_pred = clf.predict(x_test)
print(confusion_matrix(y_test, y_pred))
print("Accuracy of the model using Random Classifier is: ", accuracy_score(y_test, y_pred))
print("Recall of the model using Random Classifier is: ", recall_score(y_test, y_pred))
print("Precision of the model using Random Classifier is: ", precision_score(y_test, y_pred))
print("F1 Score of the model using Random Classifier is: ", f1_score(y_test, y_pred))

print(classification_report(y_test, y_pred))


[[987  20]
 [ 26 967]]
Accuracy of the model using Random Classifier is:  0.977
Recall of the model using Random Classifier is:  0.973816717019134
Precision of the model using Random Classifier is:  0.9797365754812564
F1 Score of the model using Random Classifier is:  0.9767676767676767
              precision    recall  f1-score   support

           0       0.97      0.98      0.98      1007
           1       0.98      0.97      0.98       993

    accuracy                           0.98      2000
   macro avg       0.98      0.98      0.98      2000
weighted avg       0.98      0.98      0.98      2000



## __Support Vector Machines(SVM) Classification using Sci-kit Learn__

In [25]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)
svclassifier = SVC(kernel='linear', gamma = 'scale', shrinking = False)
svclassifier.fit(x_train, y_train)

SVC(kernel='linear', shrinking=False)

In [26]:
y_pred = svclassifier.predict(x_test)

In [27]:
print("Accuracy of the model using SVM Classifier is: ", accuracy_score(y_test, y_pred))
print("Recall of the model using SVM Classifier is: ", recall_score(y_test, y_pred))
print("Precision of the model using SVM Classifier is: ", precision_score(y_test, y_pred))
print("F1 Score of the model using SVM Classifier is: ", f1_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy of the model using SVM Classifier is:  0.9215
Recall of the model using SVM Classifier is:  0.8932527693856999
Precision of the model using SVM Classifier is:  0.9456289978678039
F1 Score of the model using SVM Classifier is:  0.9186949766960124
[[956  51]
 [106 887]]
              precision    recall  f1-score   support

           0       0.90      0.95      0.92      1007
           1       0.95      0.89      0.92       993

    accuracy                           0.92      2000
   macro avg       0.92      0.92      0.92      2000
weighted avg       0.92      0.92      0.92      2000



In [28]:
svclassifier = SVC(kernel='poly', gamma = 'scale', shrinking = False)
svclassifier.fit(x_train, y_train)

SVC(kernel='poly', shrinking=False)

In [29]:
y_pred = svclassifier.predict(x_test)

In [30]:
print("Accuracy of the model using SVM Poly Classifier is: ", accuracy_score(y_test, y_pred))
print("Recall of the model using SVM Poly Classifier is: ", recall_score(y_test, y_pred))
print("Precision of the model using SVM Poly Classifier is: ", precision_score(y_test, y_pred))
print("F1 Score of the model using SVM Poly Classifier is: ", f1_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy of the model using SVM Poly Classifier is:  0.886
Recall of the model using SVM Poly Classifier is:  0.8187311178247734
Precision of the model using SVM Poly Classifier is:  0.9442508710801394
F1 Score of the model using SVM Poly Classifier is:  0.8770226537216828
[[959  48]
 [180 813]]
              precision    recall  f1-score   support

           0       0.84      0.95      0.89      1007
           1       0.94      0.82      0.88       993

    accuracy                           0.89      2000
   macro avg       0.89      0.89      0.89      2000
weighted avg       0.89      0.89      0.89      2000



In [51]:
svclassifier = SVC(kernel='rbf', gamma = 'scale', shrinking = False)
svclassifier.fit(x_train, y_train)

SVC(shrinking=False)

In [52]:
y_pred = svclassifier.predict(x_test)

In [53]:
print("Accuracy of the model using SVM rbf Classifier is: ", accuracy_score(y_test, y_pred))
print("Recall of the model using SVM rbf Classifier is: ", recall_score(y_test, y_pred))
print("Precision of the model using SVM rbf Classifier is: ", precision_score(y_test, y_pred))
print("F1 Score of the model using SVM rbf Classifier is: ", f1_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy of the model using SVM rbf Classifier is:  0.9705
Recall of the model using SVM rbf Classifier is:  0.9697885196374623
Precision of the model using SVM rbf Classifier is:  0.9707661290322581
F1 Score of the model using SVM rbf Classifier is:  0.9702770780856425
[[978  29]
 [ 30 963]]
              precision    recall  f1-score   support

           0       0.97      0.97      0.97      1007
           1       0.97      0.97      0.97       993

    accuracy                           0.97      2000
   macro avg       0.97      0.97      0.97      2000
weighted avg       0.97      0.97      0.97      2000



Multiple Linear Regression using Scikit Learn

In [45]:
regressor = LinearRegression()
regressor.fit(x_train, y_train)

LinearRegression()

In [75]:
coeff_df = pd.DataFrame(regressor.coef_, x.columns, columns=['Coefficient'])
coeff_df

Coefficient
MU_dots       -3.462210e-02
MU_hypens      8.943356e-02
MU_at          3.179230e-03
MU_and        -6.588937e-02
MU_percentage  2.701702e-02
MU_slash       2.000640e-01
MU_star       -1.942890e-16
MU_comma       9.274517e-04
MU_semicolon  -1.664304e-03
MU_dollar      2.766237e-02
MU_colon      -3.316879e-01
MU_question    4.782568e-02
MU_space      -4.336809e-18
MU_underscore  4.390782e-02
MU_equal       8.714388e-02
MU_hash       -4.585584e-03
length        -8.774188e-03
age            2.074436e-01

In [76]:
y_pred = regressor.predict(x_test)

In [77]:
linear_reg = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})
linear_reg

Actual  Predicted
1364       1   0.746014
2004       1   0.754865
3109       0   0.283383
336        1   0.659635
568        0   0.166398
...      ...        ...
2861       1   0.881275
6078       0   0.043670
8798       1   1.178037
3152       1   0.700073
4622       1   0.579691

[2000 rows x 2 columns]

In [78]:
print("Accuracy of the model using Multiple Linear Regression Classifier is: ", explained_variance_score(y_test, y_pred))
# print(classification_report(y_test, y_pred))

Accuracy of the model using Multiple Linear Regression Classifier is:  0.5737536113568996


In [79]:
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Mean Absolute Error: 0.2574969170724968
Mean Squared Error: 0.10658125437199834
Root Mean Squared Error: 0.3264678458470272


In [ ]:
from sklearn import metrics
# We are going to run it for k = 1 to 15 and will be recording testing accuracy, plotting it, showing confusion matrix and classification report:
Range_k = range(1,15)
scores = {}
scores_list = []
for k in range_k:
   classifier = KNeighborsClassifier(n_neighbors=k)
   classifier.fit(X_train, y_train)
   y_pred = classifier.predict(X_test)
   scores[k] = metrics.accuracy_score(y_test,y_pred)
   scores_list.append(metrics.accuracy_score(y_test,y_pred))
result = metrics.confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(result)
result1 = metrics.classification_report(y_test, y_pred)
print("Classification Report:",)
print (result1)

## __Logistic Regression__

In [34]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)
logistic_regression = LogisticRegression()
logistic_regression.fit(x_train,y_train)
y_pred=logistic_regression.predict(x_test)

In [35]:
cnf_matrix = confusion_matrix(y_test, y_pred)
cnf_matrix

array([[1773,  186],
       [ 154, 1847]], dtype=int64)

In [36]:
print("Accuracy using Logistic Regression: ",accuracy_score(y_test, y_pred))
print("Precision using Logistic Regression: ",precision_score(y_test, y_pred))
print("Recall using Logistic Regression: ",recall_score(y_test, y_pred))
print("F1 score using Logistic Regression: ",f1_score(y_test, y_pred))

Accuracy using Logistic Regression:  0.9141414141414141
Precision using Logistic Regression:  0.9085095917363503
Recall using Logistic Regression:  0.9230384807596201
F1 score using Logistic Regression:  0.9157164105106594


KNN Algorithm

In [59]:
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(x_train, y_train)
y_pred = knn.predict(x_test)
print("Accuracy of the model using KNN Algorithm is: ", accuracy_score(y_test, y_pred))
print("Precision of the model using KNN Algorithm is: ", precision_score(y_test, y_pred))
print("Recall of the model using KNN Algorithm is: ", recall_score(y_test, y_pred))
print("F1 Score of the model using KNN Algorithm is: ", f1_score(y_test, y_pred))

Accuracy of the model using KNN Algorithm is:  0.964
Precision of the model using KNN Algorithm is:  0.9646821392532795
Recall of the model using KNN Algorithm is:  0.9627391742195368
F1 Score of the model using KNN Algorithm is:  0.9637096774193548


In [60]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(x_train, y_train)
y_pred = knn.predict(x_test)
print("Accuracy of the model using KNN Algorithm is: ", accuracy_score(y_test, y_pred))
print("Precision of the model using KNN Algorithm is: ", precision_score(y_test, y_pred))
print("Recall of the model using KNN Algorithm is: ", recall_score(y_test, y_pred))
print("F1 Score of the model using KNN Algorithm is: ", f1_score(y_test, y_pred))

Accuracy of the model using KNN Algorithm is:  0.964
Precision of the model using KNN Algorithm is:  0.9628140703517588
Recall of the model using KNN Algorithm is:  0.9647532729103726
F1 Score of the model using KNN Algorithm is:  0.9637826961770624


In [56]:
knn = KNeighborsClassifier(n_neighbors=10)
knn.fit(x_train, y_train)
y_pred = knn.predict(x_test)
print("Accuracy of the model using KNN Algorithm is: ", accuracy_score(y_test, y_pred))
print("Precision of the model using KNN Algorithm is: ", precision_score(y_test, y_pred))
print("Recall of the model using KNN Algorithm is: ", recall_score(y_test, y_pred))
print("F1 Score of the model using KNN Algorithm is: ", f1_score(y_test, y_pred))

Accuracy of the model using KNN Algorithm is:  0.959
Precision of the model using KNN Algorithm is:  0.9691040164778579
Recall of the model using KNN Algorithm is:  0.9476334340382678
F1 Score of the model using KNN Algorithm is:  0.9582484725050917
